### ISSUE TITLE
Enable redirections 

### ISSUE THREAD

**Issue by Sergiodero** [MobilityData/elrond.gtfs.org#81]
**Context**

The new content structure in Elrond will significantly move the location of several pieces of content from gtfs.org. We need to make sure that all current gtfs.org pages are redirected to the location in the new (Elrond) structure.

**Request**

@fredericsimard I've put together a [list with all redirects](https://docs.google.com/spreadsheets/d/1BSURXoWBTyE_xLqlPbdAd0sITZjgM_nO8g0NvI4JzLQ/edit?usp=sharing), could you help us setting up this?

**Comment by fredericsimard** [comment]
#86 adresses this. Closing
