### ISSUE TITLE
Set up fetch script to pull content from Google/transit

### ISSUE THREAD

**Issue by Sergiodero** [MobilityData/elrond.gtfs.org#82]
**Context**

As the structure in Elrond has changed the path of several files, we need to set up the fetch script again to flag whenever a change has been made to google/transit so that we can update in gtfs.org

**Request**

@fredericsimard I've put together a [list of the pages](https://docs.google.com/spreadsheets/d/1BSURXoWBTyE_xLqlPbdAd0sITZjgM_nO8g0NvI4JzLQ/edit?usp=sharing) (see second tab) that need to be fetched from google/transit, could you help us setting up the script? lmk if you have any questions regarding the list. Thanks!

**Comment by fredericsimard** [comment]
This will be resolved with the action I prepared that will be put in place the day of the launch.
